### ISSUE TITLE
Knex can't acess db.sqlite when are hosting in vercel

### ISSUE THREAD

**Issue by RafaelGoulartB** [RafaelGoulartB/next.js-ecommerce#39]
When host the project in Vercel, knex can't read db.sqlite.

**Comment by quangminhit94** [comment]
Now heroku-postbuild script entry is no longer required because heroku now automatically running npm run build .
To fix this please open package.json then edit like this:
{
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start -p $PORT"
  }
}
